# SPDX-FileCopyrightText: Copyright (c) 2023 - 2026 NVIDIA CORPORATION & AFFILIATES.
# SPDX-FileCopyrightText: All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

_target_: rollout.FIGConvUNetTimeConditionalRollout
_convert_: all

# Input/output channels
in_channels: 2                       # thickness + time
out_channels: 3                      # displacement offset (xyz)

# Architecture
kernel_size: 3
hidden_channels: [16, 16, 16]      # channels at each level
num_levels: 2                        # number of down/up levels
num_down_blocks: 1
num_up_blocks: 1
mlp_channels: [256, 256]

# Spatial domain
aabb_max: [2.0, 2.0, 2.0]
aabb_min: [-2.0, -2.0, -2.0]
voxel_size: null

# Grid resolutions (factorized implicit grids)
# Format: Uses res_mem_pair resolver (memory_format_enum, resolution_tuple)
resolution_memory_format_pairs:
  - [b_xc_y_z, [2, 64, 64]]
  - [b_yc_x_z, [64, 2, 64]]
  - [b_zc_x_y, [64, 64, 2]]

# Position encoding
use_rel_pos: true
use_rel_pos_embed: true
pos_encode_dim: 16

# Communication and sampling
communication_types: ["sum"]
to_point_sample_method: "graphconv"
neighbor_search_type: "knn"
knn_k: 16
reductions: ["mean"]

use_scalar_output: false
has_input_features: true

# Pooling (for global features if needed)
pooling_type: "max"
pooling_layers: [2]

# Rollout parameters
num_time_steps: ${training.num_time_steps}
